spring:
  application:
    name: getpet
  datasource:
    url: jdbc:h2:mem:getpet
    driverClassName: org.h2.Driver
    username: root
    password: root
    initialization-mode: embedded
    platform: h2
  jpa:
    hibernate:
      ddl-auto: create

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
